approvals:
  # PR needs at least 2 approvals
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)$"
  veto:
    # veto/blocking a PR = comment that matches this regex
    pattern: "^(:\\-1:|👎)$"
